### ISSUE TITLE
建议把第三方的依赖也打包到git上

### ISSUE THREAD

**Issue by omegatao** [xuhao1/FlightAgentX#2]
INCLUDEPATH += ../third_party/opencv-4.4.0-build/include
INCLUDEPATH +=../third_party/eigen-3.3.7
INCLUDEPATH += ../third_party/dlib/include
INCLUDEPATH += ../third_party/YAML_CPP/include
INCLUDEPATH += ../third_party/onnxruntime-win-x86-1.5.1/include

建议将pro中这几个依赖也放到git中，这样大家贡献代码的时候更方便，不用到处找依赖了。

**Comment by xuhao1** [comment]
> INCLUDEPATH += ../third_party/opencv-4.4.0-build/include
> INCLUDEPATH +=../third_party/eigen-3.3.7
> INCLUDEPATH += ../third_party/dlib/include
> INCLUDEPATH += ../third_party/YAML_CPP/include
> INCLUDEPATH += ../third_party/onnxruntime-win-x86-1.5.1/include
> 
> 建议将pro中这几个依赖也放到git中，这样大家贡献代码的时候更方便，不用到处找依赖了。

Sure, the Windows System haven't got a good package manage system makes it really inconvenient on dependency. I will upload the third_party reference as a achieve file later.

Windows系统没有包管理导致依赖确实很麻烦，我之后会把依赖库打包为压缩文件上传。

**Comment by omegatao** [comment]
OK, after you uploaded the third_party reference I will try to contribute some code to this project.

**Comment by xuhao1** [comment]
@omegatao The third party is here
https://drive.google.com/file/d/1RZcPLo44ZskggyeplkRspSGumy_n88Q1/view?usp=sharing
I will add it to readme later

**Comment by omegatao** [comment]
@xuhao1 I noticed that you are using some features that introduced since qt 5.14. I think it is useful for other developers if you can also explain your developing environment in the README file.
